# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#000000" }

# Hovered
hovered         = { bg = "#dbdbdb", bold = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#5E409D", italic = true, underline = true }
find_position = { fg = "#800042", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#66800B", bg = "#66800B" }
marker_copied   = { fg = "#f3d000", bg = "#f3d000" }
marker_cut      = { fg = "#AF3029", bg = "#AF3029" }

# Tab
tab_active   = { fg = "#000000", bg = "#ffffff" }
tab_inactive = { fg = "#595959", bg = "#dfdfdf" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#9f9f9f" }

# Highlighting
syntect_theme = "~/.config/yazi/Catppuccin-macchiato.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#e0e0e0", bg = "#e0e0e0" }

# Mode
[mode]
normal_main = { fg = "#F3F3FF", bg = "#354FCF", bold = true }
normal_alt  = { bg = "#F3F3FF", fg = "#354FCF" }

select_main = { fg = "#ECF7ED", bg = "#316500", bold = true }
select_alt = { bg = "#ECF7ED", fg = "#316500" }

unset_main  = { fg = "#FFF1F0", bg = "#972500", bold = true }
unset_alt = { bg = "#FFF1F0", fg = "#972500" }

# Progress
progress_label  = { fg = "#000000", bold = true }
progress_normal = { fg = "#4FAA09", bg = "#8FEF00" }
progress_error  = { fg = "#fff1f0", bg = "#d00000" }

# Permissions
perm_type = { fg = "#4385BE" }
perm_read = { fg = "#6f5500" }
perm_write = { fg = "#AF3029" }
perm_exec = { fg = "#66800B" }
perm_sep = { fg = "#575653" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#9f9f9f" }
title    = { fg = "#193668" }
value    = { fg = "#000000" }
selected = { fg = "#0031a9", bg = "#bfc9ff" }

# : }}}


# : Select {{{

[pick]
border   = { fg = "#6F6E69" }
active   = { fg = "#800042" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#6F6E69" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#f0f0f0" }
cand            = { fg = "#006800" }
rest            = { fg = "#5E409D" }
desc            = { fg = "#800042" }
separator       = "  "
separator_style = { fg = "#575653" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#0031a9" }
run   = { fg = "#006800" }
desc    = { fg = "#8a290f" }
hovered = { bg = "#dbdbdb", bold = true }
footer  = { fg = "#000000", bg = "#dbdbdb"}

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#5E409D" },

	# Videos
	{ mime = "video/*", fg = "#6f5500" },
	{ mime = "audio/*", fg = "#6f5500" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#800042" },

	# Fallback
	{ name = "*", fg = "#000000" },
	{ name = "*/", fg = "#00663f" }
]

# : }}}
